openapi: 3.0.0

info:
  title: Blog api
  description: A simple blog api
  version: v1
  contact:
    name: Felix Orinda
    email: forinda82@gmail.com

servers:
- url: https://{username}:{port}/api/{basePath}
  description: The production API server
  variables:
    username:
      # note! no enum here means it is an open value
      default: localhost
      description: this value is assigned by the service provider, in this example `gigantic-server.com`
    port:
      enum:
        - '4300'
        - '6200'
      default: '8443'
    basePath:
      # open meaning there is the opportunity to use special base paths as assigned by the provider, default is `v2`
      default: v1
paths:
  /users:
    get:
      description: Returns all pets from the system that the user has access to
      responses:
        '200':
          description: A list of pets.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'


components:
  schemas:
    User:
      type: object
      discriminator:
        propertyName: petType
      properties:
        name:
          type: string
        petType:
          type: string
      required:
      - name
      - petType
    Comment:  ## "Cat" will be used as the discriminator value
      description: A representation of a cat
      allOf:
      - $ref: '#/components/schemas/User'
      - type: object
        properties:
          huntingSkill:
            type: string
            description: The measured skill for hunting
            enum:
            - clueless
            - lazy
            - adventurous
            - aggressive
        required:
        - huntingSkill
    Like:  ## "Dog" will be used as the discriminator value
      description: A representation of a dog
      allOf:
      - $ref: '#/components/schemas/Comment'
      - type: object
        properties:
          packSize:
            type: integer
            format: int32
            description: the size of the pack the dog is from
            default: 0
            minimum: 0
        required:
        - packSize

